name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      data:
        description: "Input data from Supabase"
        required: false
        default: "{}"

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      script_output: ${{ steps.run_script.outputs.result }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run script
        id: run_script
        run: |
          echo "Input from Supabase: ${{ github.event.inputs.data }}"
          # Capture the output of your Python script
          result=$(python run_script.py)
          # Log it for GitHub Actions
          echo "Python Output: $result"
          # Expose it as an output for API access
          echo "result=$result" >> $GITHUB_OUTPUT
