name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      data:
        description: "Input data from Supabase"
        required: false
        default: "{}"

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      script_output: ${{ steps.run_python.outputs.script_output }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run script
        id: run_python
        run: |
          echo "Running script with input: ${{ github.event.inputs.data }}"
          output=$(python run_script.py)
          echo "Script output: $output"
          echo "script_output=$output" >> $GITHUB_OUTPUT
